# pre-commit configuration file

exclude: ^migrations/versions/

repos:
  # --- Black: code formatter ---
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black

  # --- isort: import sorter ---
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort

  # # --- Ruff: linter + formatter ---
  # - repo: https://github.com/astral-sh/ruff-pre-commit
  #   rev: v0.7.0
  #   hooks:
  #     - id: ruff
  #       args: ["--fix"] # رفع خودکار خطاهای قابل اصلاح


  # # --- Optional: Mypy (type checking) ---
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.11.2
  #   hooks:
  #     - id: mypy

  # --- Optional: Bandit (security checks) ---
  # - repo: https://github.com/PyCQA/bandit
  #   rev: 1.7.10
  #   hooks:
  #     - id: bandit
